sudo: false
addons:
  apt:
    packages:
      xmlsec1  # pysaml2 needs to find an xmlsec1 binary
language: python
python:
  - "2.7"
# Have Travis CI start mongodb and redis for us
services:
  - mongodb
  - redis-server
# command to install dependencies
install:
  - pip install -U setuptools
  - python setup.py develop
  - pip install nosexcover WebTest==2.0.18
# command to run tests
script:
  - nosetests
