language: python
python:
  - "2.7"
# command to run tests
script: nosetests
# Have Travis CI start a mongodb server for us
services:
  - mongodb
# pysaml2 needs to find an xmlsec1 binary
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y xmlsec1
